name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Cache build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: target
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve cached build
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Run tests
      run: cargo test --verbose
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: build
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: jetli/wasm-pack-action@v0.3.0
    - uses: actions/checkout@v2
    - name: Build WASM
      run: |
        cd wasm
        wasm-pack build --target web --release
    - name: Create Page folder
      run: |
        mkdir deploy
        mv index.html deploy
        rm deploy/pkg/.gitignore
        rm deploy/pkg/*.ts
        rm deploy/pkg/*.json
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: wasm/deploy
